### Criar evento
POST http://127.0.0.1:8080/audit-service/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Content-Type: application/json

{
  "service": "bets-service",
  "type": "CASHOUT",
  "message": "Cashout realizado na aposta 90001."
}

### Listar tudo
GET http://127.0.0.1:8080/audit-service/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json

### Filtrar por serviço
GET http://127.0.0.1:8080/audit-service/events?service=bets-service
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json

### Filtrar por tipo
GET http://127.0.0.1:8080/audit-service/events?type=LOGIN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json
