### Listar jogos
GET http://127.0.0.1:8080/bets-service/matches
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json


### Listar mercados de um jogo
GET http://127.0.0.1:8080/bets-service/markets?matchId=101
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json


### Criar uma aposta
POST http://127.0.0.1:8080/bets-service/bets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Content-Type: application/json
Accept: application/json

{
  "matchId": 101,
  "marketId": 5001,
  "selectionCode": "HOME",
  "stake": 50.0,
  "expectedOdds": 1.95,
  "idempotencyKey": "teste123"
}


### Listar apostas do usuário atual
GET http://127.0.0.1:8080/bets-service/bets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json


### Obter detalhe de uma aposta
GET http://127.0.0.1:8080/bets-service/bets/90001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json


### Fazer cashout de uma aposta
POST http://127.0.0.1:8080/bets-service/bets/90001/cashout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Content-Type: application/json
Accept: application/json

{
  "acceptAmount": 70.5
}
