### Listar histórico de apostas (todos)
GET http://127.0.0.1:8080/history-service/bets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json

### Filtrar por status (WON)
GET http://127.0.0.1:8080/history-service/bets?status=WON
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json

### Filtrar por intervalo de datas
GET http://127.0.0.1:8080/history-service/bets?from=2025-11-10T00:00:00Z&to=2025-11-13T23:59:59Z
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json

### Filtrar por nome do jogo
GET http://127.0.0.1:8080/history-service/bets?match=Corinthians
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json

### Detalhe de uma aposta
GET http://127.0.0.1:8080/history-service/bets/90001
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhdXRoLXNlcnZpY2UiLCJhdWQiOiJhdXRoLXNlcnZpY2UiLCJzdWIiOiIyMGRlODNjMC03NTFhLTRiNzgtYmE1Ny0yMTc1NGU1MDJmZWYiLCJpYXQiOjE3NjM4MzMyMTMsImV4cCI6MTc2MzgzNDExMywidHlwZSI6ImFjY2VzcyIsImVtYWlsIjoibm92b0B0ZXN0ZS5jb20iLCJyb2xlIjoiQ1VTVE9NRVIiLCJsZXZlbCI6MX0.o9Px-21DjFPsmtdkBI9VPrXZMuNpdqUZffCbL7EESKI
Accept: application/json
